### ISSUE TITLE
bug(@vtmn/svelte & @vtmn/css): button background color

### ISSUE THREAD

**Issue by sidbentifraouineatdecathlon** [Decathlon/vitamin-web#1182] opened 2022-06-17 14:48 UTC
**Description**
Sometimes I have this problem, which is probably related to the circled part.

**Steps to reproduce**
1. I refresh
2.  it’s transparent
3.  I refresh 
4. it’s primary (order whatever chosen variant color) (the cycle is random)

<img width="976" alt="Screenshot 2022-06-15 at 09 55 50" src="https://user-images.githubusercontent.com/77100520/174321774-eb36d152-4cea-494f-a6d7-c9bdbc223f7e.png">
<img width="936" alt="Screenshot 2022-06-15 at 09 55 55" src="https://user-images.githubusercontent.com/77100520/174321779-aa6b3dea-ecd9-4334-bede-803bf000eabd.png">

<img width="936" alt="Screenshot 2022-06-15 at 09 55 55" src="https://user-images.githubusercontent.com/77100520/174321986-9289c960-8818-4ad2-b247-35e6f7935a07.png">

**Expected behavior**

**Browsers affected**

- Chrome

**Version affected**
@vtmn/assets
@vtmn/css-tailwind-preset 0.33.113
@vtmn/icons 0.12.1
@vtmn/svelte 0.45.6

**Comment by lauthieb** [comment] 2022-06-22 21:17
Hi Sid,

Thanks for reporting this bug. It's very weird. Do you have a better example in order to reproduce? Maybe with our storybook documentation. Because I don't understand why this happens randomly...

For your screenshot, it's normal because it comes from the "normalize" step from Tailwind CSS

See : 
- https://v2.tailwindcss.com/docs/preflight
- modern-normalize v1.1.0  https://github.com/sindresorhus/modern-normalize

Thanks in advance for your answer & help.

**Comment by lauthieb** [comment] 2022-06-27 14:49
I close it for now

> Hi Sid,
> 
> Thanks for reporting this bug. It's very weird. Do you have a better example in order to reproduce? Maybe with our storybook documentation. Because I don't understand why this happens randomly...
> 
> For your screenshot, it's normal because it comes from the "normalize" step from Tailwind CSS
> 
> See :
> 
> * https://v2.tailwindcss.com/docs/preflight
> * modern-normalize v1.1.0  https://github.com/sindresorhus/modern-normalize
> 
> Thanks in advance for your answer & help.

I close it for now, feel free to reopen if you succeed to have a case to reproduce more precisely.
Thanks Sid!

**Closed by lauthieb** 2022-06-27 14:49 UTC
Labels: bug 🐛, CSS 🎨, Svelte 🟠, v0 ⛳️

**Comment by sidbentifraouineatdecathlon** [comment] 2022-06-27 16:21
Hi @lauthieb, this was due to a miss-configuration of mine, the preprocess plugin wasn't enabled in `SvelteKit`. My bad.
Thank you for you support! 🙏
