### ISSUE TITLE
bug: popover not closing sometimes

### ISSUE THREAD

**Issue by AlbertNambiaparambil** [Decathlon/vitamin-web#1244] opened 2022-08-25 14:46 UTC
**Describe the bug**
The popover component is supposed to close when you click outside the component.
In the delivery page of the funnel in Decathlon Spain, we noticed that the component is not closing when you click outside the component (in certain areas). 

**Steps to reproduce the behavior:**
1. Go to [this page](https://www.decathlon.es/es/p/mp/izas/sandalia-deportiva-unisex-para-caminar-o-senderismo-comodas-y-ligeras-tyn-izas/_/R-p-8f18c65e-8fc9-4fb0-84d2-5a288c29948a?mc=8f18c65e-8fc9-4fb0-84d2-5a288c29948a_c255&c=MULTICOLOR)
2. Add the product to the basket.
3. Click on the basket and proceed to the delivery page of the checkout funnel.
4. Scroll down to 'Recogida en tienda' (Collect from store)
<img width="333" alt="image" src="https://user-images.githubusercontent.com/93610673/186696330-da8637a2-39af-499c-a6c8-152f71b5e144.png">
5.  Click on the 'information' button.
6. Once the popover component is open, try to close it. Chances are that it won't close properly.
-->

Feel free to comment on this if you want more details
Albert

**Comment by GaspardMathon** [comment] 2022-08-25 15:15
Hi @AlbertNambiaparambil, thanks for raising this issue.
Can you provide the url for us to check this issue please ? I think you forgot to set it in your comment :) 

We will take a look at this ASAP

**Comment by AlbertNambiaparambil** [comment] 2022-08-25 15:24
Hello @GaspardMathon 
Thanks for pointing it out. I have edited the description and included the link.

**Comment by thibault-mahe** [comment] 2022-08-26 07:06
Hello @AlbertNambiaparambil, thanks for reaching us!

The process you provide is a bit heavy to reproduce since it requires creating an account. Maybe you could provide us with a dev account, a preprod or even a code sandbox? If you can directly identify the issue, you also could propose a PR  and I would be happy to help you reviewing it.

As far as I can see, it might either be an issue with somme overriding css (that keep the popover open) on your side, or an issue with the button/span not losing focus. Currently, the [popover component](https://github.com/Decathlon/vitamin-web/blob/main/packages/sources/css/src/components/overlays/popover/src/index.css#L67-L77) is based on CSS pseudo classes [`:focus-within`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within), thus the issue can also be related to a child of your component not losing focus.

Not sure if the Svelte integration is related to the issue here, but maybe @Tlahey has already dealt with a similar bug?

**Comment by romuleald** [comment] 2022-09-02 14:17
Do you have a `pointer: none;` somewhere since it seems you make the block behind unclickable?

**Comment by thibault-mahe** [comment] 2022-09-05 07:23
Good idea @romuleald. @AlbertNambiaparambil could you check on this please? On your video it seems that when your pointer is still on your block it cannot focus out of your tooltip since the block is unclickable. As soon as your pointer leaves the block, the tooltip becomes blurred as it should.

Thanks for the recording by the way, but it remains hard to fix without a reproductible demo 😬

**Comment by thibault-mahe** [comment] 2022-09-20 10:22
Hi! It has been 15 days since the last comment suggesting a fix. I close this issue that seems irrelevant now. Feel free to reopen it if this issue still persist :)

**Closed by thibault-mahe** 2022-09-20 10:22 UTC
Labels: bug 🐛, CSS 🎨, v0 ⛳️
