### ISSUE TITLE
bug(@vtmn/css): when no labelText provided to Select, the chevron is not aligned with the default value

### ISSUE THREAD

**Issue by MaelthiS** [Decathlon/vitamin-web#1303] opened 2022-11-10 07:57 UTC
**Describe the bug**
When no label is provided to the VtmnSelect component, the chevron icon is not aligned with the default select option.

**Steps to reproduce**
In Storybook, remove the labelText from the Select component. The chevron icon should not be aligned with the default option in vertical alignement..

**Expected behavior**

   - Chrome

**Version affected**
Last version

**Comment by MaelthiS** [comment] 2022-11-10 07:57
![image](https://user-images.githubusercontent.com/97453800/201033505-4986feb2-5eaf-45d6-ba08-fba09d6e02a7.png)

**Comment by lauthieb** [comment] 2022-11-10 13:27
Thanks @MaelthiS for this issue. I'll let @thibault-mahe answer you as soon as possible.

**Comment by thibault-mahe** [comment] 2022-11-16 17:34
Hi @MaelthiS thanks for reaching us :) 
Indeed it seems that the chevron position is based on the flow of the component, since it is only floated on the right. The issue is that the label, the chevron and the select itself belong to the same parent, and then to the same flow. Removing the label modifies the position of the chevron unfortunately :/ 

I could make an easy fix using flex or removing the chevron from the flow (absolute positioning), but the issue is that both fixes require we add a container so the chevron and the select are the only siblings, and this could bring some breaking changes for the CSS package users using the classes without this container...

I'll discuss this subject with @gaspard-mathon and @lauthieb and come back to you. Thanks !

**Comment by MaelthiS** [comment] 2022-11-18 14:24
Thanks for the analysis @thibault-mahe !

**Comment by thibault-mahe** [comment] 2022-11-29 12:56
Hi @MaelthiS,
unfortunately the fix for this issue may bring breaking changes. Would it be ok for you to make a "temporary" fix on your side, by adding for example a negative margin or a transform. It would give use some time to rework entirely the component and to resubmit a new one in a next version (v1) during 2023 ?

Thanks!

**Closed** 2023-04-07 13:02 UTC
Labels: bug 🐛, CSS 🎨, next ⛳️, build 🏗

**Comment by Tlahey** [comment] 2023-04-07 13:12
Now it's possible to bump the vtmn version on major, we can introduce breaking changes @thibault-mahe ? 
So it is possible to fix this issue ?

**Comment by lauthieb** [comment] 2023-04-07 13:16
@Tlahey, yes we can.
Let's track this in https://github.com/Decathlon/vitamin-web/issues/1020
